### ISSUE TITLE
Depressions - errors and suggestions of improvement

### ISSUE THREAD

**Issue by stefankinell** [rphlo/rusty-pullauta#83]
I write this here as an issue, because in some parts it is an issue. But some parts might be considered an idéa or change request. And both these seems to be inherited from the original kartapullautin.

**First - the issue.**
I find places where depressions are presented as contours. Here is one example: https://kartor.gokartor.se/#17/60.33863/15.79572
It is located in Säter in Sweden.

As a comparison, the competition orienteering map for the area can be viewed at https://www.omaps.net/se?id=64162

The contours from rusty-pullauta looks like this:
![rusty-pullauta-säter](https://github.com/rphlo/rusty-pullauta/assets/59049892/3952eaf7-2709-44bb-b498-a491c3055c0e)

The contours from OCAD DEM creation looks like this:
![ocad-säter](https://github.com/rphlo/rusty-pullauta/assets/59049892/ae8222d3-7270-40f6-a440-1f4f532b6c1e)

The error lies in that there are a couple of depressions that are neglected. The big one to the left in the image and the one center lower part.

Terrain shadow of the area can be viewed at https://minkarta.lantmateriet.se/plats/3006/v2.0/?e=544627&n=6689316&z=12&mapprofile=terrangskuggning&name=S%C3%A4ter%20depressions&layers=%5B%5B%223%22%5D%2C%5B%221%22%5D%2C%5B%224%22%5D%5D

**Second - idéas of improvement**
_1. More depression lines._
I think there are to few lines that are marked as depressions. If I am not mistaken, it is one or two in the bottom. I would argue for more levels marked as depression. In one way it seems OCAD perhaps are to many levels. But I realize it is also difficult to say when to stop. I would ask for four lines.

_2. Formlines as depressions_ 
Today the formlines are not marked as depressions. I would really like that. Today I use instead the intermediate depressions from contours file as depression form lines, and then you get more depressions than you need sometimes.

Two laz-files for this area are uploaded at https://drive.google.com/drive/folders/16P05V6y9vorOIVwwO3GNtNm3TOkUAAl3?usp=sharing

**Comment by Jagge** [comment]
Right, KP limits detection of depresson contours to smaller than certain size/length contours for performance reasons. If you look closely all those not purple depressions are longer/larger than the largest purple. The thinking went along lines larger ones can be figured without color forsurrounding contours, but small ones necessarily not. I guess Rusty versio could just lift the old limit.

**Comment by stefankinell** [comment]
> Thanks for the report!
> 
> As you mention this is an issue already present in the original KP. So far the goal has been to be copy conform to original KP, so I would consider change for this after the version 1.0.0 release, that I think of as the starting point of new development, and also as the end of the transcription of original KP.

I agree and understand. I just wanted to capture my thoughts when I saw the issue and thought about how I probably would have wanted things to evolve.

**Comment by stefankinell** [comment]
> Right, KP limits detection of depresson contours to smaller than certain size/length contours for performance reasons. If you look closely all those not purple depressions are longer/larger than the largest purple. The thinking went along lines larger ones can be figured without color forsurrounding contours, but small ones necessarily not. I guess Rusty versio could just lift the old limit.

Thanks for the backstory! Then I understand the logics. We had a long discussion in the Facebook group for my Swedish map where I asked about how to display depressions - violet contours vs brown with automatic slope lines. In that discussion I also became aware of the depressions I pictured above, and others, where it looks like a hill, but it is a depression.

But reading your explanation it looks like it should not be to hard to find out how to increase the threshold of length of depression lines. 

Thanks!

**Comment by stefankinell** [comment]
Nice!
My instinct tells me we should us a parameter. Where the default without having the parameter set would be the standard 181 from kartapullautin. But letting the parameter be standard 181 and that 0 (or 10000) means no limit.

I am just trying out what happens if I delete the check. But my first results are outputting strand contours in the junction of two laz-files. I will compile the program again and see if I get it right before we do some actual changes.

Do you think the changes to introduce form lines in depressions are difficult to do? I have not looked at that algorithm myself yet. I just realize that if I rerun the data with more depression lines, I can not use the intermediate depression lines as form lines. Then I have to fix the form line depression lines first.

**Comment by stefankinell** [comment]
I will add three new (already added the one about formlines).

For the other two, I am currently testing older versions to see if I can find where the strange contours at borders are introduced. Then I will file a new issue for that as well.

As for depression max size. I can rewrite a new one for that as well. But I realize when I removed the limit that I don't get all the depression lines I thought I would. Although it is a big step forward anyhow. I'll see if I can change the code myself and file a pull request - with a parameter.

**Comment by stefankinell** [comment]
Replaced by: 
Formlines-output file also to indicate depressions #91
Batch mode - rusty-pullauta does not recognize neighboring laz-files? #92 
Enabling larger depression contours #94

**Comment by stefankinell** [comment]
Replaced by:
Formlines-output file also to indicate depressions https://github.com/rphlo/rusty-pullauta/issues/91
Batch mode - rusty-pullauta does not recognize neighboring laz-files? https://github.com/rphlo/rusty-pullauta/issues/92
Enabling larger depression contours https://github.com/rphlo/rusty-pullauta/issues/94
